import 'dart:convert';

class PregnancyResponseModel {
  int? UId;
  int? Weight;
  int? Height;
  String? DatePregnancy;

  PregnancyResponseModel(
      {this.UId, this.Weight, this.Height, this.DatePregnancy});

  PregnancyResponseModel.fromJson(Map<String, dynamic> json) {
    UId = json['UId'];
    Weight = json['Weight'];
    Height = json['Height'];
    DatePregnancy = json['DatePregnancy'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['UId'] = this.UId;
    data['Weight'] = this.Weight;
    data['Height'] = this.Height;
    data['DataPregnancy'] = this.DatePregnancy;
    return data;
  }
}

class Autogenerated {
  int? UId;
  int? Weight;
  int? Height;
  String? DatePregnancy;

  Autogenerated({this.UId, this.Weight, this.Height, this.DatePregnancy});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    UId = json['UId'];
    Weight = json['Weight'];
    Height = json['Height'];
    DatePregnancy = json['DatePregnancy'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['UId'] = this.UId;
    data['Weight'] = this.Weight;
    data['Height'] = this.Height;
    data['DatePregnancy'] = this.DatePregnancy;
    return data;
  }
}
